### ISSUE TITLE
can this run on raspberrypi architecture (arm32v7)?

### ISSUE THREAD

**Issue by arrikhan** [SteppingHat/docker-cgate-server#1]
Am looking to run cgate on raspberrypi 3B+ but the architcture isn't specified for this image.

What architecture does this image support?

**Comment by SteppingHat** [comment]
The CGate server itself should be able to run on any architecture, however the base image the container uses may only support amd64. If you find this is the case, I can create a tag that specifically targets the arm32v7 architecture.

**Comment by SteppingHat** [comment]
The CGate server itself should be able to run on any architecture, similarly the base image that is being used should be able to support multiple architectures, amd64 and arm32v7 alike. If you find any issues using the container, I can look into a creating a solution that specifically targets the arm32v7 architecture.

**Comment by arrikhan** [comment]
I've managed to build my own but I'm a noob to docker. So far it's working ok. I will publish mine for any other Pi lovers out there. I'll leave it to you to choose whether or not to add an extra architecture on your repo. No need to if you have no platform/use for it.

**Comment by SteppingHat** [comment]
If you like, submit a pull request and have the compatibility merged in 😄
